# Values used for the deployed application.
replicaCount: 2
service:
  name: annotations-rw-neo4j
  systemCode: annotations-rw-neo4j
env:
  SHOULD_CONSUME_MESSAGES: true
  SHOULD_FORWARD_MESSAGES: true
  CONSUMER_GROUP: annotations-rw-neo4j
  CONSUMER_TOPICS: ConceptAnnotations,NativeCmsMetadataPublicationEvents
  PRODUCER_TOPIC: PostConceptAnnotations
  KAFKA_LAG_TOLERANCE: 100
  LIFECYCLE_CONFIG_PATH: annotation-config.json
  JSON_SCHEMA_NAME: annotations-pac.json;annotations-next-video.json
  CONCEPT_PROPERTIES: "id;prefLabel;types"
