# Values used for the deployed application.
replicaCount: 2
service:
  name: suggestions-rw-neo4j
  systemCode: suggestions-rw-neo4j
env:
  SHOULD_CONSUME_MESSAGES: true
  SHOULD_FORWARD_MESSAGES: false
  CONSUMER_GROUP: suggestions-rw-neo4j
  CONSUMER_TOPIC: ConceptSuggestions
  KAFKA_LAG_TOLERANCE: 100
  LIFECYCLE_CONFIG_PATH: suggestion-config.json
