# Values used for the deployed application.
replicaCount: 2
service:
  name: suggestions-rw-neo4j
env:
  SHOULD_CONSUME_MESSAGES: false
  SHOULD_FORWARD_MESSAGES: false
  LIFECYCLE_CONFIG_PATH: suggestion-config.json
